/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ResultaterImport } from './routes/resultater'
import { Route as KamperImport } from './routes/kamper'
import { Route as IndexImport } from './routes/index'
import { Route as ResultaterSpillerIdImport } from './routes/resultater_.$spillerId'

// Create/Update Routes

const ResultaterRoute = ResultaterImport.update({
  path: '/resultater',
  getParentRoute: () => rootRoute,
} as any)

const KamperRoute = KamperImport.update({
  path: '/kamper',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ResultaterSpillerIdRoute = ResultaterSpillerIdImport.update({
  path: '/resultater/$spillerId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/kamper': {
      id: '/kamper'
      path: '/kamper'
      fullPath: '/kamper'
      preLoaderRoute: typeof KamperImport
      parentRoute: typeof rootRoute
    }
    '/resultater': {
      id: '/resultater'
      path: '/resultater'
      fullPath: '/resultater'
      preLoaderRoute: typeof ResultaterImport
      parentRoute: typeof rootRoute
    }
    '/resultater/$spillerId': {
      id: '/resultater/$spillerId'
      path: '/resultater/$spillerId'
      fullPath: '/resultater/$spillerId'
      preLoaderRoute: typeof ResultaterSpillerIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  KamperRoute,
  ResultaterRoute,
  ResultaterSpillerIdRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/kamper",
        "/resultater",
        "/resultater/$spillerId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/kamper": {
      "filePath": "kamper.tsx"
    },
    "/resultater": {
      "filePath": "resultater.tsx"
    },
    "/resultater/$spillerId": {
      "filePath": "resultater_.$spillerId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
